apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers: []
spec:
  destination:
    namespace: appsample
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/thirtynine96/argocd-example-apps
    targetRevision: HEAD
